name: Release

on:
  release:
    types: [released]

jobs:
  push:
    permissions:
      contents: read
      packages: write
    # TODO - SHA
    uses: NetChris/workflows/.github/workflows/release-dotnet-build-test-pack-push-default.yml@separate-workflows-for-nuget-org
    secrets: inherit
