name: Release

on:
  release:
    types: [released]

jobs:
  push:
    permissions:
      contents: read
      packages: write
    uses: NetChris/workflows/.github/workflows/release-dotnet-build-test-pack-push-default.yml@6753ed25deacfc53e292f92ba38bee45012a4279
    secrets: inherit
